[package]
distribution = "2201.8.6"
org = "ballerinax"
name = "guidewire.insnow"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Insurance", "Guidewire", "Cloud API"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-guidewire.insnow"

[build-options]
observabilityIncluded = false

[platform.java17]
graalvmCompatible = true
